config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#findmaterial'

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/findmaterial'
  post 'static_pages/findmaterial'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/findmaterial',   to: 'static_pages#findmaterial',   via: 'get'
  match '/findmaterial',   to: 'static_pages#findmaterial',   via: 'post'

  get '/contact', to: redirect('https://vk.com/write13246897')

  resources :propunits
  resources :matprops
  resources :materials
  resources :gosts
  resources :matpropvalues

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/matpropvalue.rb
class Matpropvalue < ApplicationRecord
#  belongs_to :material
#  belongs_to :property
end

app/controllers/matpropvalues_controller.rb
class MatpropvaluesController < ApplicationController

  def new
    @matpropvalue = Matpropvalue.new
    @matprops = Matprop.all
    @materials = Material.all.order(:name)
  end

  helper_method :sort_column, :sort_direction

  def index
    @matpropvalues = Matpropvalue.order(sort_column + ' ' + sort_direction)
  end

  def edit
    @matpropvalue = Matpropvalue.find(params[:id])

    @matprops = Matprop.all
    @materials = Material.all.order(:name)
    @matprop = Matprop.find(@matpropvalue.property_id)
    @material = Material.find(@matpropvalue.material_id)
  end

  def show
    @matpropvalue = Matpropvalue.find(params[:id])

    @matprop = Matprop.find(@matpropvalue.property_id)
    @propunit = Propunit.find(@matprop.unit_id)
    @material = Material.find(@matpropvalue.material_id)
  end

  def create
    # render plain: params[:value].inspect

    @matpropvalue = Matpropvalue.new(matpropvalue_params)

    if @matpropvalue.save
      redirect_to @matpropvalue
    else
      render 'new'
    end

  end

  def update
    @matpropvalue = Matpropvalue.find(params[:id])

    if @matpropvalue.update(matpropvalue_params)
      redirect_to @matpropvalue
    else
      render 'edit'
    end
  end

  def destroy
    @matpropvalue = Matpropvalue.find(params[:id])
    @matpropvalue.destroy

    redirect_to matpropvalues_path
  end

  private
  def matpropvalue_params
    params.require(:matpropvalue).permit(:material_id, :property_id, :num_value)
  end

  def sort_column
    Matpropvalue.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/helpers/matpropvalues_helper.rb
module MatpropvaluesHelper
end

app/views/matpropvalues/_errorcheck.html.erb
<% if @matpropvalue.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@matpropvalue.errors.count, "error") %> prohibited
      this value from being saved:
    </h2>
    <ul>
      <% @matpropvalue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/matpropvalues/edit.html.erb
<h1>Правка значения</h1>

<%= form_with(model: @matpropvalue, local: true) do |form| %>

  <%= render 'errorcheck' %>

  <p>
    <%= form.label "Материал" %><br>
    <%= form.collection_select :material_id,  @materials, :id, :name, prompt: true, selected: @matpropvalue.material_id %>
  </p>

  <p>
    <%= form.label "Свойство" %><br>
    <%= form.collection_select :property_id,  @matprops, :id, :name, prompt: true, selected: @matpropvalue.property_id %>
  </p>

  <p>
    <%= form.label "Значение" %><br>
    <%= form.number_field :num_value, :step => 0.01 %>
  </p>

  <p>
    <%= form.submit "Обновить значение" %>
  </p>

<% end %>

<%= link_to 'Назад', matpropvalues_path %>

app/views/matpropvalues/index.html.erb
<h1>Список всех значений свойств</h1>

<table class="greyGridTable">
  <thead>
  <tr>
    <th><%= sortable "id", "№" %></th>
    <th>Материал</th>
    <th>Свойство</th>
    <th>Значение</th>
    <th>Ед измерения</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tfoot>
  <tr>
    <th colspan="8"></th>
  </tr>
  </tfoot>

  <% @matpropvalues.each do |matpropvalue| %>
    <tr>
      <td><%= matpropvalue.id %></td>
      <td><%= Material.find(matpropvalue.material_id).name %></td>
      <td><%= Matprop.find(matpropvalue.property_id).name %></td>
      <td><%= matpropvalue.num_value %></td>
      <td><%= Propunit.find(Matprop.find(matpropvalue.property_id).unit_id).name %></td>
      <td><%= link_to 'Просмотр', matpropvalue_path(matpropvalue) %></td>
      <td><%= link_to 'Правка', edit_matpropvalue_path(matpropvalue) %></td>
      <td><%= link_to 'Удаление', matpropvalue_path(matpropvalue),
                      method: :delete,
                      data: { confirm: 'Вы уверены в удалении этого значения?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Новый', new_matpropvalue_path %></td>

app/views/matpropvalues/new.html.erb
<h1>Новое значение</h1>

<%= form_with scope: :matpropvalue, url: matpropvalues_path, local: true do |form| %>

  <%= render 'errorcheck' %>

  <p>
    <%= form.label "Материал" %><br>
    <%= form.collection_select :material_id,  @materials, :id, :name, prompt: true %>
  </p>

  <p>
    <%= form.label "Свойство" %><br>
    <%= form.collection_select :property_id,  @matprops, :id, :name, prompt: true %>
  </p>

  <p>
    <%= form.label "Значение" %><br>
    <%= form.number_field :num_value, :step => 0.01 %>
  </p>

  <p>
    <%= form.submit "Создать значение" %>
  </p>

<% end %>

<%= link_to 'Назад', matpropvalues_path %>

app/views/matpropvalues/show.html.erb
<h1>Просмотр значения</h1>

<p><strong>Значение:</strong></p>
<p>У материала <%= @material.name %> параметр <%=  @matprop.name %> равен
  <%=  @matpropvalue.num_value %> <%=  @propunit.name %>

  <%= link_to 'Правка', edit_matpropvalue_path(@matpropvalue) %>
  <%= link_to 'Удаление', matpropvalue_path(@matpropvalue),
            method: :delete,
            data: { confirm: 'Вы уверены в удалении этого значения?' } %></p>
<%= link_to 'Назад', matpropvalues_path %>