config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#findmaterial'

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/findmaterial'
  post 'static_pages/findmaterial'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/findmaterial',   to: 'static_pages#findmaterial',   via: 'get'
  match '/findmaterial',   to: 'static_pages#findmaterial',   via: 'post'

  get '/contact', to: redirect('https://vk.com/write13246897')

  resources :propunits
  resources :matprops
  resources :materials
  resources :gosts
  resources :matpropvalues

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/propunit.rb
class Propunit < ApplicationRecord
  has_many :matprops
end

app/controllers/propunits_controller.rb
class PropunitsController < ApplicationController

  def new
    @propunit = Propunit.new
  end

  helper_method :sort_column, :sort_direction

  def index
    @propunit = Propunit.order(sort_column + ' ' + sort_direction)
  end

  def edit
    @propunit = Propunit.find(params[:id])
  end

  def show
    @propunit = Propunit.find(params[:id])
  end

  def create
   # render plain: params[:propunit].inspect

   @propunit = Propunit.new(propunit_params)

   if @propunit.save
     redirect_to @propunit
   else
     render 'new'
   end
  end

  def update
    @propunit = Propunit.find(params[:id])

    if @propunit.update(propunit_params)
      redirect_to @propunit
    else
      render 'edit'
    end
  end

  def destroy
    @propunit = Propunit.find(params[:id])
    @propunit.destroy

    redirect_to propunits_path
  end

  private
  def propunit_params
    params.require(:propunit).permit(:name)
  end

  def sort_column
    Propunit.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/helpers/propunits_helper.rb
module PropunitsHelper
end

app/views/propunits/_errorcheck.html.erb
<% if @propunit.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@propunit.errors.count, "error") %> prohibited
      this unit from being saved:
    </h2>
    <ul>
      <% @propunit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/propunits/edit.html.erb
<h1>Правка единицы измерения</h1>

<%= form_with(model: @propunit, local: true) do |form| %>

  <%= render 'errorcheck' %>

  <p>
    <%= form.label "Название:" %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit "Обновить единицу измерения" %>
  </p>

<% end %>

<%= link_to 'Назад', propunits_path %>

app/views/propunits/index.html.erb
<h1>Список всех единиц измерения</h1>

<table class="greyGridTable">
  <thead>
  <tr>
    <th><%= sortable "id", "№" %></th>
    <th><%= sortable "name", "Название" %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tfoot>
  <tr>
    <th colspan="5"></th>
  </tr>
  </tfoot>
  <% @propunit.each do |propunit| %>
    <tr>
      <td><%= propunit.id %></td>
      <td><%= propunit.name %></td>
      <td><%= link_to 'Просмотр', propunit_path(propunit) %></td>
      <td><%= link_to 'Правка', edit_propunit_path(propunit) %></td>
      <td><%= link_to 'Удаление', propunit_path(propunit),
                      method: :delete,
                      data: { confirm: 'Вы уверены в удалении этой единицы измерения?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Новый', new_propunit_path(@propunit) %></td>

app/views/propunits/new.html.erb
<h1>Новая единица измерения</h1>

<%= form_with scope: :propunit, url: propunits_path, local: true do |form| %>

  <%= render 'errorcheck' %>

  <p>
    <%= form.label "Название:" %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit "Создать единицу измерения" %>
  </p>

<% end %>

<%= link_to 'Назад', propunits_path %>

app/views/propunits/show.html.erb
<h1>Просмотр единицы измерения</h1>

<p>
  <strong>Ед. измерения:</strong>
  <%= @propunit.name %> <%= link_to 'Правка', edit_propunit_path(@propunit) %>
  <%= link_to 'Удаление', propunit_path(@propunit),
              method: :delete,
              data: { confirm: 'Вы уверены в удалении этой единицы измерения?' } %>
</p>

<%= link_to 'Назад', propunits_path %>