config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#findmaterial'

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/findmaterial'
  post 'static_pages/findmaterial'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/findmaterial',   to: 'static_pages#findmaterial',   via: 'get'
  match '/findmaterial',   to: 'static_pages#findmaterial',   via: 'post'

  get '/contact', to: redirect('https://vk.com/write13246897')

  resources :propunits
  resources :matprops
  resources :materials
  resources :gosts
  resources :matpropvalues

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gost.rb
class Gost < ApplicationRecord
end

app/controllers/gosts_controller.rb
class GostsController < ApplicationController

  def new
    @gost = Gost.new
  end

  helper_method :sort_column, :sort_direction

  def index
    @gosts = Gost.order(sort_column + ' ' + sort_direction)
  end

  def edit
    @gost = Gost.find(params[:id])
  end

  def show
    @gost = Gost.find(params[:id])
  end

  def create
    #   render plain: params[:propunit].inspect

    @gost = Gost.new(gost_params)

    if @gost.save
      redirect_to @gost
    else
      render 'new'
    end
  end

  def update
    @gost = Gost.find(params[:id])

    if @gost.update(gost_params)
      redirect_to @gost
    else
      render 'edit'
    end
  end

  def destroy
    @gost = Gost.find(params[:id])
    @gost.destroy

    redirect_to gosts_path
  end

  private
  def gost_params
    params.require(:gost).permit(:name,:caption)
  end

  def sort_column
    Gost.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/helpers/gosts_helper.rb
module GostsHelper
end

app/views/gosts/_errorcheck.html.erb
<% if @gost.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@gost.errors.count, "error") %> prohibited
      this Gost from being saved:
    </h2>
    <ul>
      <% @gost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/gosts/edit.html.erb
<h1>Правка ГОСТа</h1>

<%= form_with(model: @gost, local: true) do |form| %>

  <%= render 'errorcheck' %>

  <p>
    <%= form.label 'Наименование' %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label 'Заголовок' %><br>
    <%= form.text_area :caption, :cols => 50, :rows => 5 %>
  </p>

  <p>
    <%= form.submit "Обновить ГОСТ" %>
  </p>

<% end %>

<%= link_to 'Назад', gosts_path %>

app/views/gosts/index.html.erb
<h1>Список всех ГОСТов</h1>

<table class="greyGridTable">
  <thead>
  <tr>
    <th><%= sortable "id", "№" %></th>
    <th><%= sortable "name", "Номер" %></th>
    <th><%= sortable "caption", "Наименование" %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tfoot>
  <tr>
    <th colspan="5"></th>
  </tr>
  </tfoot>
  <% @gosts.each do |gost| %>
    <tr>
      <td><%= gost.id %></td>
      <td><%= gost.name %></td>
      <td><%= gost.caption %></td>
      <td><%= link_to 'Просмотр', gost_path(gost) %></td>
      <td><%= link_to 'Правка', edit_gost_path(gost) %></td>
      <td><%= link_to 'Удаление', gost_path(gost),
                      method: :delete,
                      data: { confirm: 'Вы уверены в удалении этого ГОСТ?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Новый', new_gost_path(@gost) %></td>

app/views/gosts/new.html.erb
<h1>Новый ГОСТ</h1>

<%= form_with scope: :gost, url: gosts_path, local: true do |form| %>

  <%= render 'errorcheck' %>

  <p>
    <%= form.label 'Наименование' %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label 'Заголовок' %><br>
    <%= form.text_area :caption, :cols => 50, :rows => 5 %>
  </p>

  <p>
    <%= form.submit "Создать ГОСТ" %>
  </p>

<% end %>

<%= link_to 'Назад', gosts_path %>

app/views/gosts/show.html.erb
<h1>Просмотр ГОСТа</h1>

<p>
  <strong>Название: </strong>
  <%= @gost.name %> - <em><%= @gost.caption%></em> <%= link_to 'Правка', edit_gost_path(@gost) %>
  <%= link_to 'Удаление', gost_path(@gost),
    method: :delete,
    data: { confirm: 'Вы уверены в удалении этого ГОСТ?' } %>
</p>

<%= link_to 'Назад', gosts_path %>