config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#findmaterial'

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/findmaterial'
  post 'static_pages/findmaterial'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/findmaterial',   to: 'static_pages#findmaterial',   via: 'get'
  match '/findmaterial',   to: 'static_pages#findmaterial',   via: 'post'

  get '/contact', to: redirect('https://vk.com/write13246897')

  resources :propunits
  resources :matprops
  resources :materials
  resources :gosts
  resources :matpropvalues

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Разработан
    <a href="http://dennismorosoff.com/">Денисом Морозовым</a> (с) 2018
  </small>
  <nav>
    <ul>
      <li><%= link_to "О проекте",   about_path %></li>
      <li><%= link_to "Связаться", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Rosstat App", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Главная",    root_path %></li>
          <li><%= link_to 'Значения', matpropvalues_path %></li>
          <li><%= link_to 'Материалы', materials_path %></li>
          <li><%= link_to 'ГОСТы', gosts_path %></li>
          <li><%= link_to 'Свойства', matprops_path %></li>
          <li><%= link_to 'Ед измерения', propunits_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_caption(yield(:full_title), yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                            "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>

</html>